from typing import List, Protocol, Optional
from medical_llm_workflow.Domain.tasks.models import TaskRecord


class WorkflowContextPort(Protocol):
    """工作流上WorkflowContextPort下文协议，解耦任务层与具体上下文实现。"""
    def get_previous_task_record(self, task_id: str) -> TaskRecord: ...
    # def get_all_prev_task_records(self, task_id: str) -> List[TaskRecord]: ...
    def append_task_record(self, record: TaskRecord) -> None: ...
    def get_task_record(self, task_id: str) -> TaskRecord: ...
    def get_all_records(self) -> List[TaskRecord]: ...
    def get_last_task_record(self) -> Optional[TaskRecord]: ...